---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: citrix-node-controller
rules:
  - apiGroups: ["*"]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: ["*"]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["*"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts", "clusterroles", "clusterrolebindings", "namespaces"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["*"]
    resources: ["serviceaccounts", "clusterroles", "clusterrolebindings", "namespaces"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["ipamblocks"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: citrix-node-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: citrix-node-controller
subjects:
- kind: ServiceAccount
  name: citrix-node-controller
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: citrix-node-controller
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-cnc-router
rules:
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["ipamblocks"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-cnc-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-cnc-router
subjects:
- kind: ServiceAccount
  name: kube-cnc-router
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-cnc-router
  namespace: default
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: cnc-citrix-node-controller
  namespace: citrix-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: citrix-node-controller
      app.kubernetes.io/instance: cnc
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: citrix-node-controller
        app.kubernetes.io/instance: cnc
    spec:
      serviceAccountName: citrix-node-controller
      containers:
      - name: citrix-node-controller
        image: "quay.io/citrix/citrix-k8s-node-controller:2.2.11"
        imagePullPolicy: Always
        env:
        - name: EULA
          value: "yes"
        - name: NS_IP
          value: "xxxxxxx"
        - name: NS_USER
          valueFrom:
            secretKeyRef:
              name: nslogin
              key: username
        - name: NS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nslogin
              key: password
        - name: NETWORK
          value: "172.18.3.0/24"
        - name: REMOTE_VTEPIP
          value: "xx.xx.xx.yy"
        - name: VNID
          value: "175"
        - name: VXLAN_PORT
          value: "8472"
        - name: CNI_TYPE
          value: <CNI-NAME like calico, flannel>
        - name: "CNC_ROUTER_NAME"
          value: kube-cnc-router
        - name: "CNC_CONFIGMAP"
          value: citrix-node-controller